"""Rebuild WikiForge's flat Taillée identity from paths and local Barlow outlines."""

from pathlib import Path
import json
from fontTools.ttLib import TTFont
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "static/brand/v1"
NAME = "WikiForge"
INK, PAPER, HEAT = "#171918", "#EFEBD9", "#E8EF42"
# Traced from proposal 01: same angular silhouette and open diagonal incision.
FLAME_BOX = "0 0 192 272"
FLAME = "M107 14L137 62L91 172L151 122L183 207L153 259H83L121 170L43 259L10 210L31 149L111 62Z"
SMALL = "M8 1L10 4L7 9L11 6L13 12L11 15H6L9 10L5 15L3 12L4 8L8 4Z"


def wordmark():
    font = TTFont(ROOT / "static/fonts/arcade/BarlowCondensed-Black.ttf")
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    scale = 100 / font["head"].unitsPerEm
    cursor, points = 0, []
    for char in NAME:
        glyph = glyphs[cmap[ord(char)]]
        bounds = BoundsPen(glyphs)
        glyph.draw(bounds)
        x0, y0, x1, y1 = bounds.bounds
        points += [(cursor + x0 * scale, -y1 * scale), (cursor + x1 * scale, -y0 * scale)]
        cursor += glyph.width * scale + .2
    left, top = min(x for x, _ in points), min(y for _, y in points)
    width = max(x for x, _ in points) - left + 4
    height = max(y for _, y in points) - top + 4
    pen = SVGPathPen(glyphs, ntos=lambda n: f"{n:.3f}".rstrip("0").rstrip("."))
    cursor = 0
    for char in NAME:
        glyph = glyphs[cmap[ord(char)]]
        glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, cursor - left + 2, -top + 2)))
        cursor += glyph.width * scale + .2
    return f"0 0 {width:.3f} {height:.3f}", pen.getCommands(), width / height


def svg(content, width, height):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}" role="img" aria-label="{NAME}"><title>{NAME}</title>{content}</svg>\n'


def flame(x, y, height, color=HEAT):
    return f'<g transform="translate({x} {y}) scale({height / 272})"><path d="{FLAME}" fill="{color}"/></g>'


def save(name, content):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(content, encoding="utf-8")


def build():
    box, letters, ratio = wordmark()
    identity = ROOT / "src/lib/brand/artwork.js"
    identity.parent.mkdir(parents=True, exist_ok=True)
    values = {"brandName": NAME, "flameViewBox": FLAME_BOX, "flamePath": FLAME,
              "compactFlamePath": SMALL, "wordmarkViewBox": box, "wordmarkPath": letters}
    identity.write_text("// Generated by scripts/generate-brand-assets.py; edit its vector master.\n" +
                        "".join(f"export const {key} = {json.dumps(value)};\n" for key, value in values.items()), encoding="utf-8")
    for name, color in (("yellow", HEAT), ("cream", PAPER), ("ink", INK)):
        save(f"symbol-{name}.svg", svg(flame(37.65, 0, 256, color), 256, 256))
        save(f"wordmark-{name}.svg", f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}" role="img" aria-label="{NAME}"><title>{NAME}</title><path d="{letters}" fill="{color}"/></svg>\n')
    for name, mark, ink in (("dark", HEAT, PAPER), ("light", INK, INK), ("mono-cream", PAPER, PAPER), ("mono-ink", INK, INK)):
        text = f'<svg x="104" y="28" width="{88 * ratio}" height="88" viewBox="{box}"><path d="{letters}" fill="{ink}"/></svg>'
        save(f"signature-horizontal-{name}.svg", svg(flame(0, 0, 144, mark) + text, round(120 + 88 * ratio), 144))
        text = f'<svg x="24" y="282" width="312" height="{312 / ratio}" viewBox="{box}"><path d="{letters}" fill="{ink}"/></svg>'
        save(f"signature-stacked-{name}.svg", svg(flame(89.65, 12, 256, mark) + text, 360, round(298 + 312 / ratio)))
    icon = svg(f'<rect width="16" height="16" fill="{INK}"/><path d="{SMALL}" fill="{HEAT}"/>', 16, 16)
    save("favicon.svg", icon)
    (ROOT / "src/lib/assets/favicon.svg").write_text(icon, encoding="utf-8")
    (ROOT / "static/favicon.svg").write_text(icon, encoding="utf-8")
    save("pinned-tab.svg", svg(flame(37.65, 0, 256, "#000000"), 256, 256))
    for size in (180, 192, 512):
        height = size * .76
        content = f'<rect width="{size}" height="{size}" fill="{INK}"/>' + flame((size - height * 192 / 272) / 2, size * .12, height)
        save(f"icon-{size}.svg", svg(content, size, size))
    for size in (192, 512):
        height = size * .64
        save(f"icon-maskable-{size}.svg", svg(f'<rect width="{size}" height="{size}" fill="{INK}"/>' + flame((size - height * 192 / 272) / 2, size * .18, height), size, size))
    social = f'<rect width="1200" height="630" fill="{INK}"/>' + flame(80, 108, 414)
    social += f'<svg x="440" y="205" width="660" height="{660 / ratio}" viewBox="{box}"><path d="{letters}" fill="{PAPER}"/></svg>'
    save("social-card.svg", svg(social, 1200, 630))
    placeholder = svg(f'<rect width="600" height="450" fill="{INK}"/><rect x="20" y="20" width="560" height="410" fill="none" stroke="{PAPER}" stroke-opacity=".25"/>' +
                      flame(230, 42, 200) + f'<svg x="160" y="285" width="280" height="{280 / ratio}" viewBox="{box}"><path d="{letters}" fill="{PAPER}"/></svg>', 600, 450)
    save("card-placeholder.svg", placeholder)
    (ROOT / "static/card-placeholder.svg").write_text(placeholder, encoding="utf-8")
    manifest = {"id": "/", "name": NAME, "short_name": NAME, "lang": "fr", "start_url": "/", "scope": "/",
                "display": "standalone", "background_color": INK, "theme_color": INK,
                "icons": [{"src": f"/brand/v1/icon-{size}.png", "sizes": f"{size}x{size}", "type": "image/png", "purpose": "any"} for size in (192, 512)] +
                         [{"src": f"/brand/v1/icon-maskable-{size}.png", "sizes": f"{size}x{size}", "type": "image/png", "purpose": "maskable"} for size in (192, 512)]}
    (ROOT / "static/site.webmanifest").write_text(json.dumps(manifest, ensure_ascii=False, indent="\t") + "\n", encoding="utf-8")
    print("Generated flat Taillée master, outlined wordmark, signatures, icon sources and manifest.")


if __name__ == "__main__":
    build()
